;; Quickly compile and load files needed for the jtms/jtre

(compile-file "unify.lisp")
(compile-file "funify.lisp")
(compile-file "jdata.lisp")
(compile-file "jinter.lisp")
(compile-file "jrules.lisp")
(compile-file "jtms.lisp")
(compile-file "my-test.lisp")
(compile-file "dikb-inference-test")
(compile-file "test-dissertation-dikb")
(compile-file "UPIA-dikb-jtms.lisp")

(load "unify.lisp")
(load "funify.lisp")
(load "jdata.lisp")
(load "jinter.lisp")
(load "jrules.lisp")
(load "jtms.lisp")
;;(load "test-dissertation-dikb.lisp")
(load "UPIA-dikb-jtms.lisp")
